import os

KEY_LENGTH = 256
BLOCK_LENGTH = 16

DEFAULT_PASSWORD_LENGTH = 25
KEY_CHARS = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'

DIR = os.path.dirname(__file__) + '/data/'
KEY_FILE = DIR + 'key'
PASSWORD_FILE = DIR + 'data'
PASSWORD_FILE_BACKUP = DIR + 'data-last'
PASSWORD_FILE_PLAINTEXT = DIR + 'tmp'

PAD_BYTE = b'\x00'
CLIPBOARD_COMMAND = 'xsel'
